name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step to check out the code
      - uses: actions/checkout@v4

      # Step to set up Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Grant execute permission for the gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step to build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run unit tests
      # - name: Run Unit Tests
      #   run: ./gradlew test

      # # Run lint checks
      # - name: Run Lint
      #   run: ./gradlew lint
